version: '2'

# starts 4 docker containers running minio server instances. Each
# minio server's web interface will be accessible on the host at port
# 9001 through 9004.
services:
  minio1:
    image: minio/minio
    ports:
      - "9001:9000"
    volumes:
      - /media/tim/ee59953b-8db8-4f6d-a27d-8c6cb2e0ac95/minio/1:/export
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: zzz123zzz
    command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export
  minio2:
    image: minio/minio
    ports:
      - "9002:9000"
    volumes:
      - /media/tim/ee59953b-8db8-4f6d-a27d-8c6cb2e0ac95/minio/2:/export
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: zzz123zzz
    command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export
  minio3:
    image: minio/minio
    ports:
      - "9003:9000"
    volumes:
      - /media/tim/ee59953b-8db8-4f6d-a27d-8c6cb2e0ac95/minio/3:/export
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: zzz123zzz
    command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export
  minio4:
    image: minio/minio
    ports:
      - "9004:9000"
    volumes:
      - /media/tim/ee59953b-8db8-4f6d-a27d-8c6cb2e0ac95/minio/4:/export
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: zzz123zzz
    command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export
